#!/bin/sh

set -e

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--debian-installer-distribution daily \
	--distribution sid \
	--linux-packages "linux-image linux-headers" \
	--source false \
	--apt-recommends false \
	--archive-areas "main contrib non-free" \
	--bootloaders grub-efi \
	--firmware-binary false \
	--firmware-chroot false \
	--loadlin false \
	--win32-loader false \
	--debug true \
	--quiet false \
	--verbose true \
	"${@}"
